const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const file=path.join(root,'components/studio.tsx');
let s=fs.readFileSync(file,'utf8');
function replace(a,b){if(!s.includes(a))throw new Error('Missing source: '+a.slice(0,60));s=s.replace(a,b);}
replace("import { projects, contact, type Project }", "import { Tilt } from '@/components/ui/tilt';\nimport { projects, contact, brandCount, projectCount, type Project }");
replace('className="project-card"','className={`project-card ${project.format === "landscape" ? "landscape" : ""}`}');
replace('    <button className="project-visual"','    <Tilt className="project-tilt"><button className="project-visual"');
replace('    </button>\n    <div className="project-caption">','    </button></Tilt>\n    <div className="project-caption">');
replace('<span>9:16</span></span>','<span>{project.format === "landscape" ? "16:9" : "9:16"}</span></span>');
replace('className="film-shell"','className={`film-shell ${project.format === "landscape" ? "wide-film" : ""}`}');
replace('<dd>Vertical · 9:16</dd>','<dd>{project.format === "landscape" ? "Landscape · 16:9" : "Vertical · 9:16"}</dd>');
s=s.replaceAll('Jasveer','Jasvir').replaceAll('JASVEER','JASVIR');
replace('<span className="logo-mark">j<span>.</span></span>','<img className="actual-logo" src="/brand/js-monogram.webp" alt="JS video editor logo" width="46" height="46" />');
replace('EDITOR & STORYTELLER','SINGH / VIDEO EDITOR');
replace('The work <span>06</span>','The work <span>{projectCount}</span>');
replace('<div className="hero-reels">','<Tilt className="hero-tilt" rotationFactor={13}><div className={`hero-reels ${heroMotion ? "motion-on" : "motion-off"}`}>');
replace('</button></div></div><div className="hero-bottom">','</button></div></Tilt></div><div className="hero-bottom">');
replace("['All work','Brand stories','Social & ads','Automotive']","['All work','Brand stories','Social & ads','Spaces & places','Food & wellness','Automotive']");
replace("{f === 'All work' && <span>06</span>}","{f === 'All work' && <span>{projectCount}</span>}");
replace('<div className="portrait-composition">','<Tilt className="portrait-composition" rotationFactor={8}>');
replace('<Star className="portrait-star" /></div><div className="about-copy">','<Star className="portrait-star" /></Tilt><div className="about-copy">');
replace('<strong>06</strong><span>SELECTED FILMS</span>','<strong>{projectCount}</strong><span>SELECTED FILMS</span>');
replace('<strong>05</strong><span>FEATURED BRANDS</span>','<strong>{String(brandCount).padStart(2,"0")}</strong><span>FEATURED BRANDS</span>');
replace('<strong>9:16</strong><span>MADE FOR MOBILE</span>','<strong>02</strong><span>FILM FORMATS</span>');
replace('<section id="services"', '<section className="identity-section section-wrap"><a className="identity-banner" href="/brand/linkedin-banner.png" target="_blank" rel="noreferrer" aria-label="View Jasvir Singh identity banner"><img src="/brand/linkedin-banner.webp" alt="Jasvir Singh, video editor. Phone 9517717717. Email jassijattu06@gmail.com." loading="lazy" width="1584" height="396" /></a><div className="identity-links"><span>THE SIGNATURE / JASVIR SINGH</span><a href="/brand/jasvir-singh.vcf" download>Save my contact ↗</a><a href="/brand/contact-artwork.png" target="_blank" rel="noreferrer">Contact artwork ↗</a><a href="/brand/logo-original.png" target="_blank" rel="noreferrer">JS identity ↗</a></div></section>\n      <section id="services"');
replace('(contact.email || contact.whatsapp || contact.instagram)', '(contact.email || contact.phone || contact.whatsapp || contact.instagram)');
replace('<div className="contact-links">','<div className="contact-links">{contact.phone && <a href={`tel:${contact.phone.replace(/\\s/g,"")}`}>{contact.phone} ↗</a>}');
replace('<p>Your footage. Your story.<br />Let’s give it the edit it deserves.</p>','<p>Bathinda, Punjab · Working with brands everywhere.<br />Let’s give your story the edit it deserves.</p>');
fs.writeFileSync(file,s);
const layout=path.join(root,'app/layout.tsx');
fs.writeFileSync(layout,fs.readFileSync(layout,'utf8').replaceAll('Jasveer Editor','Jasvir Singh | Video Editor').replaceAll('Explore six selected films for Auto Mates, Signature Migration, Meubles Navcan, Reach On Peak, and WeCan Movers.','Explore 15 selected films across property, automotive, food, finance, and brand storytelling.').replaceAll('by Jasveer.','by Jasvir Singh.'));
console.log('Integrated 15 films, responsive landscape layouts, 21st Tilt, supplied branding, and contact details.');
